config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "dashboard#index" , as: "authenticated_root"
  end

  root to: "home#index"

  # We hit this path when we log out
  get "users", to: redirect("/")

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :validatable, :trackable

  # Ignore the trackable features, which change frequently
  audited except: [
    :sign_in_count,
    :last_sign_in_at,
    :last_sign_in_ip,
    :current_sign_in_at,
    :current_sign_in_ip,
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @page_title = "Dashboard"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<navbar>
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>
    <%= link_to 'Edit profile', edit_user_registration_path %>
    <%#
      This log-out link will send the delete twice, once to the correct path
      and once to dashboard. No harm, but not ideal. Seems to be an issue
      with Turbo.
    %>
    <%= button_to(
      'Logout',
      destroy_user_session_path,
      method: :delete
    ) %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</navbar>

<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Core</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-4 px-2">

      <% if notice %>
        <p class="flash bg-green-100 text-green-600 border-green-400"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="flash bg-red-100 text-red-600 border-red-400"><%= alert %></p>
      <% end %>

      <% if user_signed_in? %>
        <navbar class="flex justify-between">
          <h1><%= @page_title %></h1>

          <div class="flex flex-col items-end">
            <%= link_to current_user.email, edit_user_registration_path %>
            <%#
              We use a button to prevent turbo from double requesting with a link,
              but style it as a link because that's the look we're going for :(
            %>
            <%= button_to(
              'logout',
              destroy_user_session_path,
              method: :delete,
              class: "px-0 text-cyan-700 hover:text-cyan-900 bg-transparent"
            ) %>
          </div>
        </navbar>
      <% end %>

      <content class="mt-4 block">
        <%= yield %>
      </content>
    </main>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>